### ISSUE TITLE
Not working in JSF Framework. 

### ISSUE THREAD

**Issue by krismisc** [mishraas/jQuery-SSN-Field-Masking#4]
Hi

I am implementing this plug in to mask SSN input and create a hidden input to store the actual value, but it is not working in JSF Framework. I tried to use it normal,its working good there. Could you please help me out?

**Comment by mishraas** [comment]
@krismisc I am new to JSF though but I try to see whats the issue to integrate this component with JSF. In the mean while it would be great if you can log some further details as what is breaking;exception logs if any; or share any sample app if you have.
