### ISSUE TITLE
Input field is cleared when mask function is used inside blur event in jquery

### ISSUE THREAD

**Issue by ssshettigar** [mishraas/jQuery-SSN-Field-Masking#5]
Hi Ashutosh,

I'm using plugin to mask and unmask SSN during blur and focus event. I found that blur event is clearing entered SSN.  But when I used focusout event instead of blur event, input field value was retained. Do you know why?

Code Snippet
<!DOCTYPE html>

<html>
<head>
    <title>Test App</title>
    <script type="text/javascript" src="jquery.js"></script>
    <script type="text/javascript" src="jquery.maskedinput.min.js"></script>
    <script type="text/javascript" src="jquery.maskssn.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#ssn').blur(function () {
                $('#ssn').unmask().maskSSN('999-99-9999', { maskedChar: 'X', maskedCharsLength: 5 });
            }).focus(function () {
                $('#ssn').unmask().mask('999-99-9999');
            });            
        });

    </script>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <input name="ID" id="PID" type="text" />
            <label for="ssn">SSN</label>
            <input type="text" id="ssn" name="ssn" />
            <label for="First Name">First Name</label>
            <input type="text" id="firstName" name="firstName" />
        </div>
    </form>
</body>
</html>

**Comment by mishraas** [comment]
Hi,

I would not recommend this approach of re-initialization of the component on every blur/focus-out event.
The plugin relies on blur event of the element and performs the neccessary actions like clearing the field value, validating it and masking as needed.
You may need to revisit your design. If further clarifications needed, you may drop me a message at ashutosh2289@gmail.com . I would be happy to help.

Thanks,
Ashutosh
